### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tailhook** [cactorium/node-cint64#1]
Hi!

I've tried to use this library and it seems to leak memory. I'm doing a lot of operations like this:
```
new Int64(this.memory).add(val).intoBuffer(this.memory)
```
And it consistenly leaks memory.

Here is at least one place that looks like it's leaking. This object is never deallocated:
https://github.com/cactorium/node-cint64/blob/cdaf3913c83c8de11a2cc42fc21574faf4704b8d/src/int64-type.h#L38

(I'm not familiar with node API, but it looks like regular C++ allocation and is not touched by garbage collector. And node's garbage-collector stats don't show memory grows, only RSS, i.e. memory stats reported by OS)

**Comment by cactorium** [comment]
Hello! I had no idea people were actually using this lol. You're correct and it was leaking memory, could you see if it's still an issue with the current master? I found two places where there were allocations that weren't being managed by Node, and flagged both of them, so it should probably not leak memory now. I'll push up a new version after I fix the all the deprecation warnings I'm getting on compilation. Would you mind posting your Node version? I'm curious to see what version this still compiles with, given the last release was two years ago

**Comment by cactorium** [comment]
Version 1.1.3 should have the fixes, I'll get around to modernizing it after finals. Please let me know if the memory leak's still happening

**Comment by tailhook** [comment]
Yes, in my case memory leak has gone. Thanks for quick response!
